### ISSUE TITLE
[FIX] Change getWidgetInfo Logic for Initial User Setting

### ISSUE THREAD

**Issue by givemethatsewon** [TryOn-A-Virtual-Fitting-Service/8Fit-server#58]
### 📢 Issue Content  
Add initial model setting logic by gender  

### 📋 Description  
- **Logic Overview**:  
  - If `gender == male`, set default model photos to `male`, `female`.  
  - If `gender == female`, set default model photos to `female`, `male`.  

- **Photo Source**:  
  - Default male and female photos are hosted in a CDN.  
  - Click "Try On" to update the model photo using the user's uploaded result.  

- **Validating Default CDN Photos**:  
  - Are existing CDN photos still valid? **YES**  

- **Decision on URL Management**:  
  - Manage default model photo URLs using **ENUM** for clarity and maintainability.  

---

### 📋 Implementation Plan  

1. **Define ENUM for Default Model URLs**  
   - Create an ENUM class to manage URLs for male and female default models.  

   ```java
   public enum DefaultModelUrl {
       MALE("https://cdn.example.com/male_model.jpg"),
       FEMALE("https://cdn.example.com/female_model.jpg");

       private final String url;

       DefaultModelUrl(String url) {
           this.url = url;
       }

       public String getUrl() {
           return url;
       }
   }
   ```

2. **Ensure Validity of CDN Photos**  
   - Regularly test and validate the CDN URLs for accessibility and performance.  

---

### ✔️ Checklist  

- [ ] Define and implement `DefaultModelUrl` ENUM class.  
- [ ] Add logic to set default model photos based on gender.  
- [ ] Integrate with "getWidgetInfo" functionality to handle updates.  
- [ ] Validate default CDN URLs and handle potential exceptions.
